### ISSUE TITLE
Update the cloud bootstrapping procedure in the root Makefile

### ISSUE THREAD

**Issue by Stephen-ONeil** [PHACDataHub/safe-inputs#142]
Either maintain it or toss it. Leaning towards maintaining it for now, since it's probably not all that stale.

Alternatively, convert it to config connector or some other infrastructure-as-code/data solution.

**Comment by Stephen-ONeil** [comment]
SOPs key and service account creation will need to be added at some point, configured it ad-hoc for now.

**Comment by Stephen-ONeil** [comment]
Domain name has changed, add that to the TODO list here.

**Comment by vedantthapa** [comment]
Completed in https://github.com/PHACDataHub/acm-core/pull/311.

The only part that isn't covered in KCC is the cloudbuild github repository connection and installation of service mesh. The latter can be done [using the fleet api](https://cloud.google.com/service-mesh/docs/onboarding/provision-control-plane#configure) from the fleet monitoring project and doesn't need additional permissions for the user.

**Comment by Stephen-ONeil** [comment]
@vedantthapa as follow up, can you delete the makefile some time and add a README.md to the kubernetes directory with a light summary of the bootstraping process? Link to the safe inputs dir in acm core, etc.

**Comment by vedantthapa** [comment]
> Completed in [PHACDataHub/acm-core#311](https://github.com/PHACDataHub/acm-core/pull/311).
> 
> The only part that isn't covered in KCC is the cloudbuild github repository connection and installation of service mesh. The latter can be done [using the fleet api](https://cloud.google.com/service-mesh/docs/onboarding/provision-control-plane#configure) from the fleet monitoring project and doesn't need additional permissions for the user.

And now the OAuth configuration as well - #499
