### ISSUE TITLE
Cloudbuild failing due to explicitly specified service account

### ISSUE THREAD

**Issue by vedantthapa** [PHACDataHub/safe-inputs#284]
Due to the changes in https://github.com/PHACDataHub/acm-core/pull/322, the cloudbuild jobs for the new project seem to be failing with the following reason - 
```
generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket', (b) use the REGIONAL_USER_OWNED_BUCKET build.options.default_logs_bucket_behavior option, or (c) use either CLOUD_LOGGING_ONLY / NONE logging options
```

A potential fix might be to [set logging options](https://cloud.google.com/build/docs/securing-builds/store-manage-build-logs) in each `cloudbuild.yaml`?

**Comment by vedantthapa** [comment]
@Stephen-ONeil thoughts?

**Comment by Stephen-ONeil** [comment]
Yeah, looks like it's necessary when using a custom service account for cloud build. Could add this to each cloud build file for now, to get builds running again:
```
options:
  logging: CLOUD_LOGGING_ONLY
```

We'll probably want them in a bucket as well, ultimately, though. If you want to go straight for setting up the bucket, giving the service account the permissions, etc, that's fine too. Not critical the builds start working again immediately, and every branch would need to rebase off main to fix their cloud builds anyway.
