### ISSUE TITLE
Configure SAST

### ISSUE THREAD

**Issue by vedantthapa** [PHACDataHub/safe-inputs#339]
One of the following should do it -
- CodeQL
  Requires public repositories. See [this](https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql).
- Semgrep
  Has [these](https://semgrep.dev/docs/semgrep-pro-vs-oss#-core-scanning-features) features with the OSS version.
- ESLint Plugin

Integration to upload results to repository's security tab would be great!

**Comment by vedantthapa** [comment]
Enabled CodeQL to try it out. Can disable if we find a better solution that fits the need.

**Comment by jichang22** [comment]
Tools of interest:
[pixee](https://www.pixee.ai/) -> integration with Github
[anchore enterprise](https://anchore.com/platform/) -> integration with Docker, AWS, Kubernetes, Azure, GCP
