### ISSUE TITLE
Probably stringify

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/safe-inputs#53]
We're logging the data sent to the API while we're figuring stuff out... which is great, but the format in the logs is pretty ugly. Switching to `console.log(JSON.stringify(data))` would produce a single readable log entry, instead of this:

![image](https://user-images.githubusercontent.com/109692/200970903-3ec54482-da72-4f33-a50f-298c2679bf5b.png)

**Comment by LilaKelland** [comment]
Yuck - sorry about that - I've JSON.stringified the data in console.log (but don't really need it anymore - so ended up removing it).  Was looking for the javascript equivalent of python logging.debug but it seems that console.debug will still print out stuff?  (Unless you write a function to set it to printing out nothing if a flag is set to true or false - should I be doing this in general?)

**Comment by sleepycat** [comment]
No worries! It's not obvious that it would behave that way at all. 
Generally I just do a basic `console.log` all the things knowing that k8s will timestamp it and it'll get swept into the central logging and handled. 
I've used [debug](https://www.npmjs.com/package/debug) in the past (possibly the equivalent of `logging.debug`) but since I know k8s/gcp is doing something "smart" if I were using it again I'd want to make sure it's not also trying to be "smart" and clashing.

GCP has some nice tools to search and alert on logs... anything that plays nice with them is good. 
Since you've removed it I'll close this.
