### ISSUE TITLE
Upgrade to GraphQL Yoga 3

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/safe-inputs#73]
Great [new release](https://the-guild.dev/blog/graphql-yoga-v3) with a few breaking changes. Migration guide for moving from 2 to 3 can be found [here](https://the-guild.dev/graphql/yoga-server/docs/migration/migration-from-yoga-v2).

**Comment by LilaKelland** [comment]
Also removed GraphQL Armor as it didn't seem to be compatible with the new GraphQL version - used @escape.tech/ plugins (https://the-guild.dev/graphql/envelop/plugins) instead. (PR #88)
