### ISSUE TITLE
Unleash Dependabot

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/safe-inputs#97]
Let's get dependabot going in this repo! Dependabot is pretty enthusiastic so [limiting it to some sane number of PRs](https://github.com/canada-ca/tracker/blob/master/.github/dependabot.yml#L1-L8) is a good idea, but once that's in place it's just a matter of enabling it in [repository config](https://github.com/PHACDataHub/safe-inputs/settings/security_analysis):
![image](https://user-images.githubusercontent.com/109692/213017754-85d9e550-5308-4629-b9c4-212cd47b12a9.png)

**Comment by Stephen-ONeil** [comment]
Done
